# Generated by Django 4.2.2 on 2023-10-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "rut",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apPaterno", models.CharField(max_length=30)),
                ("apMaterno", models.CharField(max_length=30)),
                ("FechaNacimiento", models.DateField()),
                ("correo", models.EmailField(max_length=100, unique=True)),
                ("telefono", models.CharField(max_length=10)),
                ("activo", models.IntegerField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[("estudiante", "Estudiante."), ("docente", "Docente")],
                        default="user",
                        max_length=25,
                    ),
                ),
                (
                    "tipousuario",
                    models.CharField(
                        choices=[
                            ("conductor", "Conductor."),
                            ("pasajero", "Pasajero."),
                        ],
                        default="user",
                        max_length=25,
                    ),
                ),
            ],
        ),
    ]
